[package]
name = "yaidertube"
version = "0.1.0"
edition = "2024"

[dependencies]
yt-dlp = "2.0.1"
tokio = { version = "1.49.0", features = ["full"] }
clap = { version = "4.5.60", features = ["derive"] }
